
POST http://localhost:8080/api/account/register
Content-Type: application/json

{
      "email": "test@test.com",
      "name": "Test",
      "password": "test"
}

<> 2021-09-07T221217.201.json

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-09-06T232521.500.json

###

POST http://localhost:8080/api/account/register
Content-Type: application/json

{
      "email": "test@test.com",
      "name": "Test",
      "password": "test"
}

<> 2021-09-06T232458.201.json

###

GET http://localhost:8080/api/voice/1
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "1",
  "user": {
    "id": 1
  }
}

<> 2021-09-06T205107.200.json

###

GET http://localhost:8080/api/voice/1
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "1",
  "user": {
    "id": 1
  }
}

<> 2021-09-06T205002.200.json

###

GET http://localhost:8080/api/voice/1
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "1"
}

###

GET http://localhost:8080/api/voice/1
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "name": "1"
}

###

GET http://localhost:8080/api/voice/2
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "1"
}

###

GET http://localhost:8080/api/voice/2
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "2"
}

###

GET http://localhost:8080/api/voice/1
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "2"
}

<> 2021-09-06T203659.200.json

###

GET http://localhost:8080/api/voice/1
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "1"
}

<> 2021-09-06T203649.200.json

###

GET http://localhost:8080/api/voice/1
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "1"
}

<> 2021-09-06T203629.200.json

###

GET http://localhost:8080/api/voice/2
Authorization: Basic first_user@gmail.com password1
Content-Type: application/json

{
  "id": "1"
}

<> 2021-09-06T203214.200.json

###

POST http://localhost:8080/api/account/register
Content-Type: application/json

{
      "email": "test@test.com",
      "name": "Test",
      "password": "test"
}

<> 2021-09-06T200144.201.json

###

POST http://localhost:8080/api/account/register
Content-Type: application/json

{
      "email": "test@test.com",
      "name": "Test",
      "password": "test"
}

<> 2021-09-06T200010.401.json

###

POST http://localhost:8080/api/restaurants/1/voices
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-31T205822.500.json

###

POST http://localhost:8080/api/admin/restaurants/1/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-31T205059.500.json

###

POST http://localhost:8080/api/admin/restaurants/1/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-31T205026.500.json

###

POST http://localhost:8080/api/admin/restaurants/2/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-31T204605.500.json

###

POST http://localhost:8080/api/admin/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-31T195621.201.json

###

POST http://localhost:8080/api/admin/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-31T195412.201.json

###

POST http://localhost:8080/api/admin/restaurants/2/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-30T222601.500.json

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-30T222404.500.json

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-30T222036.500.json

###

POST http://localhost:8080/api/voice
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "timeOfVoicing": "2021-08-30"
}

<> 2021-08-30T214043.500.json

###

POST http://localhost:8080/api/voice
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "timeOfVoicing": "2021-08-30"
}

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-30T213508.500.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-30T213458.201.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-30T213132.500.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-30T213125.201.json

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-30T211411.500.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-30T211257.201.json

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new",
  "price": 100
}

<> 2021-08-30T210616.500.json

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Щи1",
  "price": 1001
}

<> 2021-08-30T210517.500.json

###

POST http://localhost:8080/api/dishes
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Щи1",
  "price": 1001,
  "restaurants_id": 1
}

<> 2021-08-30T210508.404.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-30T210453.201.json

###

POST http://localhost:8080/api/dish
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Щи1",
  "price": 1001
}

<> 2021-08-30T210320.500.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-30T210243.201.json

###

POST http://localhost:8080/api/dish
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Щи1",
  "price": 1001
}

<> 2021-08-30T205845.500.json

###

POST http://localhost:8080/api/dish
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new Щи",
  "price": 1001
}

<> 2021-08-30T205725.500.json

###

POST http://localhost:8080/api/dish
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "new Щи",
  "price": 1001
}


###

DELETE http://localhost:8080/api/restaurants/3
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "id": 3
}

###

DELETE http://localhost:8080/api/restaurants/3
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{

}
###

DELETE http://localhost:8080/api/restaurants/3
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json


###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый"
}

<> 2021-08-30T204442.201.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
"name": "n Москва",
"menu": [
{
"name": "n Щи",
"price": 100
}
  ]
}

<> 2021-08-30T203125.201.json

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый",
  "menu": [
    {
      "name": "Новая еда",
      "price": 100
    },
  ]
}

###

POST http://localhost:8080/api/restaurants
Authorization: Basic admin@javaops.ru admin
Content-Type: application/json

{
  "name": "Новый",
  "menu": [
    {
      "name": "Новая еда",
      "price": 100
    }
  ]
}

<> 2021-08-30T202942.500.json

