DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;
DROP TABLE IF EXISTS meamenu_itemls CASCADE;
DROP TABLE IF EXISTS menu_item CASCADE;
DROP TABLE IF EXISTS votes CASCADE;

-- DROP SEQUENCE IF EXISTS global_seq;
--
-- CREATE SEQUENCE global_seq START WITH 100000;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR                 NOT NULL,
    email            VARCHAR                 NOT NULL,
    password         VARCHAR                 NOT NULL,
    registered       TIMESTAMP DEFAULT now() NOT NULL,
    enabled          BOOL      DEFAULT TRUE  NOT NULL,
    calories_per_day INTEGER   DEFAULT 2000  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR,
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE restaurant
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOL DEFAULT TRUE NOT NULL,
    name    VARCHAR           NOT NULL,
    address VARCHAR           NOT NULL,
    CONSTRAINT uk_restaurant UNIQUE (name, address)
);

CREATE TABLE dish_ref
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR            NOT NULL,
    price         NUMERIC(7, 2)      NOT NULL,
    enabled       BOOL  DEFAULT TRUE NOT NULL,
    restaurant_id INTEGER            NOT NULL,
    CONSTRAINT uk_dish_ref UNIQUE (name, restaurant_id)
);

CREATE TABLE menu_item
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actual_date   DATE DEFAULT now() NOT NULL,
    restaurant_id INTEGER            NOT NULL,
    dish_ref_id   INTEGER            NOT NULL,
    CONSTRAINT uk_menu_item UNIQUE (actual_date, dish_ref_id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

CREATE TABLE vote
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actual_date   DATE    NOT NULL,
    actual_time   TIME    NOT NULL,
    user_id       INTEGER NOT NULL,
    restaurant_id INTEGER NOT NULL,
    CONSTRAINT uk_vote UNIQUE (user_id, actual_date),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);